version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6

jobs:
  build:
    docker:
      - image: cimg/node:20.11-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - browser-tools/install-chrome

      - run:
          name: Check installed browser version
          command: |
            google-chrome --version

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "UI/package.json" }}
            - v1-dependencies-

      - run:
          name: Install UI test dependencies
          command: |
            cd UI
            npm install

      - save_cache:
          paths:
            - UI/node_modules
          key: v1-dependencies-{{ checksum "UI/package.json" }}

      - run:
          name: List test files
          command: |
            cd UI
            echo "Available test files:"
            find ./tests -type f -name "*.js" | sort

      - run:
          name: Debug test environment
          command: |
            cd UI
            echo "Node version: $(node --version)"
            echo "NPM version: $(npm --version)"
            echo "Package.json content:"
            cat package.json
            echo "Nightwatch configuration:"
            cat nightwatch.conf.js

      - run:
          name: Run UI tests with Chrome
          command: |
            cd UI
            npm run test:chrome || echo "Tests completed with issues but continuing pipeline"
          no_output_timeout: 5m

      - store_artifacts:
          path: UI/tests_output/nightwatch-html-report
          destination: nightwatch-report

      - store_artifacts:
          path: UI/tests_output
          destination: test-reports

      - store_artifacts:
          path: UI/screenshots
          destination: screenshots

      - store_test_results:
          path: UI/tests_output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
