version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  ui-tests:
    docker:
      - image: cimg/node:18.17-browsers
    steps:
      - checkout
      - run:
          name: Install UI Dependencies
          command: |
            cd UI
            npm install
      - run:
          name: Run UI Tests
          command: |
            cd UI
            npm test

  api-tests:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install API Dependencies
          command: |
            cd API
            npm install
      - run:
          name: Run API Tests
          command: |
            cd API
            npm test

workflows:
  version: 2
  ui-and-api-tests:
    jobs:
      - ui-tests
      - api-tests