version: 2.1

# Define reusable executors
executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.0-browsers
    working_directory: ~/project

# Define jobs
jobs:
  setup:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install root dependencies
          command: |
            if [ -f package.json ]; then
              npm ci
            fi
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  ui-tests:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install UI dependencies
          command: |
            cd UI
            npm ci
      - run:
          name: Install WebDriver dependencies
          command: |
            # Install GeckoDriver for Firefox
            wget -q https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
            tar -xzf geckodriver-v0.33.0-linux64.tar.gz
            sudo mv geckodriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/geckodriver
            
            # Install ChromeDriver (already included in the image, but let's verify)
            which chromedriver || echo "ChromeDriver not found"
            
            # Start Xvfb for headless display
            sudo apt-get update
            sudo apt-get install -y xvfb
            export DISPLAY=:99
            Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
            sleep 3
      - run:
          name: Run UI Tests with Firefox
          command: |
            cd UI
            export DISPLAY=:99
            CI=true npm run test:firefox
          environment:
            NODE_ENV: test
      - run:
          name: Run UI Tests with Chrome
          command: |
            cd UI
            export DISPLAY=:99
            CI=true npm run test:chrome
          environment:
            NODE_ENV: test
          when: always # Run even if Firefox tests fail
      - store_test_results:
          path: UI/tests_output
      - store_artifacts:
          path: UI/tests_output
          destination: ui-test-results
      - store_artifacts:
          path: UI/screenshots
          destination: ui-screenshots

  api-tests:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install API dependencies
          command: |
            cd API
            npm ci
      - run:
          name: Start Mock API Server
          command: |
            cd API
            npm run dev
          background: true
      - run:
          name: Wait for API server to be ready
          command: |
            timeout 60 bash -c 'until curl -f http://localhost:3000/api/v1/ 2>/dev/null || curl -f http://localhost:3000/ 2>/dev/null; do sleep 2; done'
      - run:
          name: Run API Tests
          command: |
            cd API
            npm test
          environment:
            NODE_ENV: test
      - store_test_results:
          path: API/reports
      - store_artifacts:
          path: API/reports
          destination: api-test-results

# Define workflows
workflows:
  version: 2
  test-pipeline:
    jobs:
      - setup
      - ui-tests:
          requires:
            - setup
      - api-tests:
          requires:
            - ui-tests # API tests run after UI tests complete