version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  ui-tests:
    docker:
      - image: cimg/node:18.17-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run UI Tests
          command: npm run test:ui || npm run cypress:run || npm test

  api-tests:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run API Tests
          command: npm run test:api || npm run mocha || npm test

workflows:
  version: 2
  ui-and-api-tests:
    jobs:
      - ui-tests
      - api-tests:
          requires:
            - ui-tests
