version: 2.1

# Define reusable executors
executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.0-browsers
    working_directory: ~/project

# Define jobs
jobs:
  setup:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install root dependencies
          command: |
            if [ -f package.json ]; then
              npm ci
            fi
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  ui-tests:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install UI dependencies
          command: |
            cd UI
            # Clean install to avoid version conflicts
            rm -rf node_modules package-lock.json
            npm install
      - run:
          name: Install and verify Chrome browser
          command: |
            echo "Checking if Chrome is installed..."
            if ! command -v google-chrome-stable &> /dev/null; then
              echo "Installing Chrome browser..."
              wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
              sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
              sudo apt-get update
              sudo apt-get install -y google-chrome-stable
            fi
            
            # Verify Chrome installation
            echo "Chrome version:"
            google-chrome-stable --version || echo "Chrome not found"
            
            # Create symlink for compatibility
            sudo ln -sf /usr/bin/google-chrome-stable /usr/bin/google-chrome || echo "Failed to create symlink"
      - run:
          name: Install and verify Firefox browser
          command: |
            echo "Checking if Firefox is installed..."
            if ! command -v firefox &> /dev/null; then
              echo "Installing Firefox browser..."
              sudo apt-get update
              sudo apt-get install -y firefox
            fi
            
            # Verify Firefox installation
            echo "Firefox version:"
            firefox --version || echo "Firefox not found"
      - run:
          name: Install WebDriver dependencies
          command: |
            # Install ChromeDriver with error handling
            echo "Installing ChromeDriver..."
            CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d. -f1)
            echo "Chrome version: $CHROME_VERSION"
            CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
            echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"
            
            wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" || { echo "Failed to download ChromeDriver"; exit 1; }
            unzip -o chromedriver_linux64.zip || { echo "Failed to unzip ChromeDriver"; exit 1; }
            chmod +x chromedriver
            sudo mv chromedriver /usr/bin/ || { echo "Failed to move ChromeDriver to /usr/bin/"; exit 1; }
            sudo ln -sf /usr/bin/chromedriver /usr/local/bin/chromedriver
            
            # Install GeckoDriver for Firefox with error handling
            echo "Installing GeckoDriver..."
            GECKO_VERSION="v0.33.0"
            wget -q "https://github.com/mozilla/geckodriver/releases/download/${GECKO_VERSION}/geckodriver-${GECKO_VERSION}-linux64.tar.gz" || { echo "Failed to download GeckoDriver"; exit 1; }
            tar -xzf geckodriver-${GECKO_VERSION}-linux64.tar.gz || { echo "Failed to extract GeckoDriver"; exit 1; }
            chmod +x geckodriver
            sudo mv geckodriver /usr/bin/ || { echo "Failed to move GeckoDriver to /usr/bin/"; exit 1; }
            sudo ln -sf /usr/bin/geckodriver /usr/local/bin/geckodriver
            
            # Verify drivers are installed correctly
            echo "ChromeDriver version:"
            chromedriver --version || echo "ChromeDriver not found"
            
            echo "GeckoDriver version:"
            geckodriver --version || echo "GeckoDriver not found"
            
            # Check binary paths
            echo "Binary paths:"
            which google-chrome-stable || echo "Chrome binary not found"
            which firefox || echo "Firefox binary not found"
            which chromedriver || echo "ChromeDriver binary not found"
            which geckodriver || echo "GeckoDriver binary not found"
      - run:
          name: Setup Xvfb for headless browser testing
          command: |
            # Install Xvfb if not already installed
            sudo apt-get update && sudo apt-get install -y xvfb
            
            # Start Xvfb
            export DISPLAY=:99
            Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
            echo "Xvfb PID: $!"
            sleep 3
          background: true
      - run:
          name: Run UI Tests with Chrome
          command: |
            cd UI
            export DISPLAY=:99
            echo "Testing Chrome connectivity..."
            google-chrome-stable --version --no-sandbox --headless --disable-gpu
            
            echo "Running Nightwatch tests with Chrome..."
            CI=true npx nightwatch --env chrome
          environment:
            NODE_ENV: test
      - run:
          name: Run UI Tests with Firefox
          command: |
            cd UI
            export DISPLAY=:99
            echo "Testing Firefox connectivity..."
            firefox --version --headless
            
            echo "Running Nightwatch tests with Firefox..."
            export NIGHTWATCH_VERBOSE=true
            export DEBUG=nightwatch*
            CI=true npx nightwatch --env firefox
          environment:
            NODE_ENV: test
          when: always # Run this step even if Chrome tests fail
      - store_test_results:
          path: UI/tests_output
      - store_artifacts:
          path: UI/tests_output
          destination: ui-test-results
      - store_artifacts:
          path: UI/screenshots
          destination: ui-screenshots

  api-tests:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install API dependencies
          command: |
            cd API
            npm ci
      - run:
          name: Start Mock API Server
          command: |
            cd API
            npm run dev
          background: true
      - run:
          name: Wait for API server to be ready
          command: |
            timeout 60 bash -c 'until curl -f http://localhost:3000/api/v1/ 2>/dev/null || curl -f http://localhost:3000/ 2>/dev/null; do sleep 2; done'
      - run:
          name: Run API Tests
          command: |
            cd API
            npm test
          environment:
            NODE_ENV: test
      - store_test_results:
          path: API/reports
      - store_artifacts:
          path: API/reports
          destination: api-test-results

# Define workflows
workflows:
  version: 2
  test-pipeline:
    jobs:
      - setup
      - ui-tests:
          requires:
            - setup
      - api-tests:
          requires:
            - setup  # Run API tests in parallel with UI tests