version: 2.1

jobs:
  ui-tests:
    docker:
      - image: cimg/node:18.16-browsers
    steps:
      - checkout
      - run:
          name: Install Firefox and GeckoDriver
          command: |
            # Install the latest version of Firefox
            sudo apt-get update
            sudo apt-get install -y firefox
            
            # Install GeckoDriver
            GECKODRIVER_VERSION="v0.33.0"
            wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
            tar -xvzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
            sudo chmod +x geckodriver
            sudo mv geckodriver /usr/local/bin/
            
            # Verify installation
            geckodriver --version
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "UI/package.json" }}
            - v1-dependencies-
      - run:
          name: Install UI Test Dependencies
          command: |
            cd UI
            npm install
      - save_cache:
          paths:
            - UI/node_modules
          key: v1-dependencies-{{ checksum "UI/package.json" }}
      - run:
          name: Run UI Tests
          command: |
            cd UI
            npm test
      - store_artifacts:
          path: UI/tests_output
          destination: ui-test-reports
      - store_test_results:
          path: UI/tests_output

  api-tests:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "API/package.json" }}
            - v1-dependencies-
      - run:
          name: Install API Test Dependencies
          command: |
            cd API
            npm install
      - save_cache:
          paths:
            - API/node_modules
          key: v1-dependencies-{{ checksum "API/package.json" }}
      - run:
          name: Run API Tests
          command: |
            cd API
            npm test
      - store_artifacts:
          path: API/reports
          destination: api-test-reports
      - store_test_results:
          path: API/reports

workflows:
  version: 2
  ui-and-api-tests:
    jobs:
      - ui-tests
      - api-tests:
          requires:
            - ui-tests